name: test-450
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Set up Docker
      uses: docker/setup-docker-action@e43656e248c0bd0647d3f5c195d116aacf6fcaf4 # v4.7.0
      with:
        daemon-config: |
          {
          "debug": true,
          "experimental": true,
              "features": {
              "containerd-snapshotter": true
              }
          }

    - name: Build Docker image
      run: |
        docker buildx build --load -t index.docker.io/local/pythonworld:${{ github.sha }} -f Dockerfile .
        docker images
        docker context ls
    - name: Get socket path
      run: |
        url=$(docker context inspect | jq -r .[0].Endpoints.docker.Host)
        socket_path=$(echo "$url" | awk -F// '{print $2}')
        echo "$socket_path"
        echo "SOCKET=$socket_path" >> $GITHUB_ENV

    - name: Run Trivy Scanner
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
      with:
        scan-type: "image"
        format: "json"
        output: "pythonworld_report.json"
        ignore-unfixed: true
        vuln-type: "os,library"
        image-ref: "index.docker.io/local/pythonworld:${{ github.sha }}"
        DOCKER-HOST: "unix://${SOCKET}"
